In [65]:
import pandas as pd
import numpy as np
data=pd.read_csv('kp_coords/data_nah2.csv')

df=data.copy()
df.loc[df['keypoint_score']<0.10,['x','y']] = np.nan

In [66]:
#get average eye distance to standardize all values by division with that value

leftEyes=data[data['part_names']=='leftEye'].drop(['pose_score','keypoint_score'],axis=1)
leftEyes=leftEyes.rename({'x':'left_x','y':'left_y'},axis=1)

rightEyes=data[data['part_names']=='rightEye'].drop(['pose_score','keypoint_score'],axis=1)
rightEyes=rightEyes.rename({'x':'right_x','y':'right_y'},axis=1)

eyes=leftEyes.merge(rightEyes, on='frame_count')
eyes['eye_dist']=(((eyes['left_x']-eyes['right_x'])**2)++(eyes['left_y']-eyes['right_y'])**2)**(1/2)

avg_eye_dist=eyes[eyes['eye_dist']!=0]['eye_dist'].mean()

In [67]:
#reformat coordinates so that nose coordinate is point of origin

df_nose = (df.loc[df['part_names'] == 'nose', ['frame_count', 'x', 'y']].copy())
df_nose.columns = ['frame_count', 'x_nose', 'y_nose']
df = df.merge(df_nose, how='left', on='frame_count')
df['x'] -= df['x_nose']
df['y'] -= df['y_nose']
df = df.drop(['x_nose','y_nose'], axis=1)
df.rename(columns={"x": "x_dist_to_nose", "y": "y_dist_to_nose"},inplace=True)

In [68]:
#standardise all values

df['x_dist_to_nose']=df['x_dist_to_nose']/avg_eye_dist
df['y_dist_to_nose']=df['y_dist_to_nose']/avg_eye_dist

In [69]:
 

df[df['keypoint_score']>0.1]

,frame_count,pose_score,part_names,keypoint_score,x_dist_to_nose,y_dist_to_nose,timestamp
0,0,0.361292,nose,0.998894,0.000000,0.000000,0
1,0,0.361292,leftEye,0.999224,0.466658,-0.343229,0
2,0,0.361292,rightEye,0.999014,-0.436058,-0.308964,0
3,0,0.361292,leftEar,0.982606,1.160584,0.239101,0
4,0,0.361292,rightEar,0.979353,-0.951020,0.276103,0
...,...,...,...,...,...,...,...
1975,116,0.390376,leftEar,0.815268,1.021582,-0.179297,7
1976,116,0.390376,rightEar,0.969567,-1.630403,0.467919,7
1977,116,0.390376,leftShoulder,0.765080,1.913235,2.946833,7
1978,116,0.390376,rightShoulder,0.822101,-1.961054,3.805590,7
1980,116,0.390376,rightElbow,0.167222,-2.537528,7.972031,7

In [70]:
df.groupby('part_names').mean()

,frame_count,pose_score,keypoint_score,x_dist_to_nose,y_dist_to_nose,timestamp
part_names,,,,,,
leftAnkle,58.0,0.353603,0.000972,NaN,NaN,3.529915
leftEar,58.0,0.353603,0.843264,1.228890,0.002339,3.529915
leftElbow,58.0,0.353603,0.124665,5.195106,4.973450,3.529915
leftEye,58.0,0.353603,0.997172,0.494697,-0.449856,3.529915
leftHip,58.0,0.353603,0.013375,1.509865,8.872805,3.529915
leftKnee,58.0,0.353603,0.005523,NaN,NaN,3.529915
leftShoulder,58.0,0.353603,0.557843,2.340970,2.975052,3.529915
leftWrist,58.0,0.353603,0.014283,6.003072,3.204317,3.529915
nose,58.0,0.353603,0.992286,0.000000,0.000000,3.529915
rightAnkle,58.0,0.353603,0.001669,NaN,NaN,3.529915
rightEar,58.0,0.353603,0.857081,-1.145254,0.090683,3.529915
rightElbow,58.0,0.353603,0.092547,-5.012565,5.434195,3.529915
rightEye,58.0,0.353603,0.997598,-0.503543,-0.420229,3.529915
rightHip,58.0,0.353603,0.018093,NaN,NaN,3.529915
rightKnee,58.0,0.353603,0.011994,NaN,NaN,3.529915
rightShoulder,58.0,0.353603,0.473702,-2.115122,3.059689,3.529915
rightWrist,58.0,0.353603,0.009183,-4.012379,5.641015,3.529915